collections:
  projects:
    output: true
    permalink: /projects/:name/

  art:
    output: true
    permalink: /art/:name/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

  - scope:
      path: ""
      type: "art"
    values:
      layout: "art"